version: '3.8'
services:
  client:
    build: ./
    container_name: client_frontend
    ports:
      - '3200:3200'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
