name: linting, testing, building

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

concurrency:
  group: ${{ github.head_ref == 'refs/heads/develop' }}
  cancel-in-progress: true
    
jobs:
  install-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3 
        
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          
      - name: Cache yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
   
      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          yarn install
      
#       DOESNT WORK
#   coverage:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [17.x]
#     needs: [ install-cache, unit-test ]
#     steps:
#     - uses: actions/checkout@v3
    
#     - name: Use Node.js ${{ matrix.node }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node }}
    
#     - name: Test
#       run: yarn test:coveralls
      
#     - name: Coveralls Parallel
#       uses: coverallsapp/github-action@master
#       with:
#         github-token: ${{ secrets.github_token }}
#         parallel: true
        
#   finish:
#     needs: coverage
#     runs-on: ubuntu-latest
#     steps:
#     - name: Coveralls Finished
#       uses: coverallsapp/github-action@master
#       with:
#         github-token: ${{ secrets.github_token }}
#         parallel-finished: true
         
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    needs: install-cache
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          
      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
          
      - name: Run lint SCSS
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          yarn lint:scss
          
      - name: Run lint TS
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          yarn lint:ts

  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    needs: install-cache
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          
      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            
      - name: Run test
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          yarn test:unit

  build-storybook:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    needs: install-cache
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          
      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
           
      - name: Build storybook
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          yarn storybook:build

  regress-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    needs: [ install-cache, build-storybook ]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          
      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Run test
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          yarn test:ui:ci
          
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    needs: [unit-test, regress-test, lint]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          
      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            
      - name: Run build
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          yarn build:prod
       
