name: linting, testing, building

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

concurrency:
  group: ${{ github.head_ref == 'refs/heads/develop' }}
  cancel-in-progress: true
    
jobs:
  install-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3 
        
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          
      - name: Cache yarn dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
   
      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true' || steps.cache-cypress-binary.outputs.cache-hit != 'true'
        run: |
          yarn install
         
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    needs: install-cache
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          
      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
          
      - name: Run lint SCSS
        run: |
          yarn lint:scss
          
      - name: Run lint TS
        run: |
          yarn lint:ts

  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    needs: install-cache
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          
      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            
      - name: Run test
        run: |
          yarn test:unit

  build-storybook:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    needs: install-cache
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          
      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
           
      - name: Build storybook
        run: |
          yarn storybook:build

  regress-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    needs: [ install-cache, build-storybook ]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          
      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Run test
        run: |
          yarn test:ui:ci
          
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    needs: [unit-test, regress-test, lint-ts, lint-scss]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          
      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            
      - name: Run build
        run: |
          yarn build:prod
       
